### ISSUE TITLE
Whats this error bro and explain briefly how to sort it out ..plz explain step by step to sort this error bcz just i m beginner

### ISSUE THREAD

**Issue by Sudharsan912** [deepakpadhi986/AI-Resume-Analyzer#4]
![IMG-20231127-WA0001](https://github.com/deepakpadhi986/AI-Resume-Analyzer/assets/137020942/d9d64ffb-b1e7-4e64-b617-66ef5e031bb1)

**Comment by deepakpadhi986** [comment]
You'll need to create a db named cv
