### ISSUE TITLE
Config file problem 

### ISSUE THREAD

**Issue by Adityak165** [deepakpadhi986/AI-Resume-Analyzer#8]
The code doesn't contain config.cfg file

**Comment by deepakpadhi986** [comment]
Please ensure that you are following the proper installation steps mentioned and also satisfy the requirements for it

Python 3.9.12
Visual Studio Build Tools (install C++ Desktop Development)

And follow the installation steps in readme

Config.cfg file will be generated from your side of you satisfy this requirements and follow the steps of installation
